### ISSUE TITLE
/usr/local/bundle/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!': 422 Unprocessable Entity (RestClient::UnprocessableEntity)

### ISSUE THREAD

**Issue by bernhardberger** [cargomedia/vagrant_cloud#20]
First off thanks for the great module, but unfortunately I'm encountering a problem I don't quite understand when using your API wrapper (automated deployment via self-hosted gitlab-ce instance):

This is the error I'm getting:

$ gem install vagrant_cloud
Building native extensions.  This could take a while...
Successfully installed unf_ext-0.0.7.2
Successfully installed unf-0.1.4
Successfully installed domain_name-0.5.20161021
Successfully installed http-cookie-1.0.3
Successfully installed mime-types-2.99.3
Successfully installed netrc-0.11.0
Successfully installed rest-client-1.8.0
Successfully installed vagrant_cloud-0.4.2
8 gems installed
$ chmod a+x atlas-deploy.rb
$ ruby ./atlas-deploy.rb $ATLAS_USERNAME $ATLAS_TOKEN $BOX_NAME $BOX_VERSION $BOX_PROVIDER

/usr/local/bundle/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!': 422 Unprocessable Entity (RestClient::UnprocessableEntity)
	from /usr/local/bundle/gems/rest-client-1.8.0/lib/restclient/request.rb:495:in `process_result'
	from /usr/local/bundle/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'
	from /usr/local/lib/ruby/2.1.0/net/http.rb:853:in `start'
	from /usr/local/bundle/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
	from /usr/local/bundle/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
	from /usr/local/bundle/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
	from /usr/local/bundle/gems/vagrant_cloud-0.4.2/lib/vagrant_cloud/account.rb:64:in `request'
	from /usr/local/bundle/gems/vagrant_cloud-0.4.2/lib/vagrant_cloud/box.rb:64:in `create_version'
	from /usr/local/bundle/gems/vagrant_cloud-0.4.2/lib/vagrant_cloud/box.rb:73:in `ensure_version'
	from ./atlas-deploy.rb:14:in `<main>'
ERROR: Build failed: exit code 1

```
This is my ruby deployment script:
# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'vagrant_cloud'

atlas_username = ARGV[0]
atlas_token = ARGV[1]
box_name = ARGV[2]
box_version = ARGV[3]
box_provider = ARGV[4]

account = VagrantCloud::Account.new(atlas_username, atlas_token)
box = account.ensure_box(box_name)
version = box.ensure_version(box_version)
provider = version.ensure_provider(box_provider)

version.relaese
puts provider.download_url
```

any ideas where it goes so wrong? and what I can do do fix the issue?

**Comment by njam** [comment]
The server responded with a non-200 status when trying to create a new box version. It's definitely not obvious from the stack trace, but you can see it here:
> 422 Unprocessable Entity (RestClient::UnprocessableEntity)

What data are you sending? What's your `ARGV`?
I would suggest that you output what is sent and received from the Atlas server in `request` in `account.rb`.

**Comment by bernhardberger** [comment]
My call is this:
`ruby ./atlas-deploy.rb $ATLAS_USERNAME $ATLAS_TOKEN $BOX_NAME $BOX_VERSION $BOX_PROVIDER`

$ATLAS_USERNAME: my username
$ATLAS_TOKEN: the token I created
$BOX_NAME:  "vagrant-deploy-test"
$BOX_VERSION: "0.0.1"
$BOX_PROVIDER: "virtualbox"

**Comment by bernhardberger** [comment]
My bad. I screwed up the environment vars. This can be closed
